### ISSUE TITLE
ERROR LOADING PLUGIN

### ISSUE THREAD

**Issue by mitch7391** [satrik/homebridge-hyperion-control#2]
Hey @satrik, thanks for your work on this plugin. I had been using it for a while now and then accidentally uninstalled it and could no longer install it fresh. I had found out from a developer on the Homebridge subreddit that it is due to the dependency `node-fetch` and the use of `>=` instead of `^`. Here is the error caused below due to the dependency:

```
[20/12/2021, 1:09:47 pm] ====================
[20/12/2021, 1:09:47 pm] ERROR LOADING PLUGIN homebridge-hyperion-control:
[20/12/2021, 1:09:47 pm] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/homebridge-hyperion-control/node_modules/node-fetch/src/index.js from /usr/local/lib/node_modules/homebridge-hyperion-control/index.js not supported.
Instead change the require of /usr/local/lib/node_modules/homebridge-hyperion-control/node_modules/node-fetch/src/index.js in /usr/local/lib/node_modules/homebridge-hyperion-control/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hyperion-control/index.js:3:13)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:132:77)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
    at async Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:106:9)
[20/12/2021, 1:09:47 pm] ====================
```

The fix just involves changing `>=` with `^` and updating the version to `2.6.6`. I have created a fork, updated it and tested it locally on my RPi; and it lets me install the plugin again now. I will quickly create a PR for you to merge this change in (I updated your version number for the patch update too).

**Comment by satrik** [comment]
@mitch7391 thanks for the PR, I've merged it. 
I missed that there was an update for node-fetch ~1 1/2 month ago.
